-- Create dag_definitions table
CREATE TABLE IF NOT EXISTS dataloaders.dag_definitions (
    dag_id VARCHAR(50) PRIMARY KEY,
    dataflow_id VARCHAR(50) REFERENCES dataloaders.dataflows(id),
    dag_name VARCHAR(255),
    description TEXT,
    dag_type VARCHAR(50),
    version VARCHAR(50),
    status VARCHAR(50),
    created_by VARCHAR(100),
    created_at BIGINT,
    last_modified BIGINT,
    tags JSONB,
    node_ids JSONB,
    edge_ids JSONB,
    global_properties JSONB,
    schedule JSONB,
    execution_plan JSONB,
    error_handling JSONB,
    monitoring JSONB,
    resource_management JSONB,
    metadata JSONB,
    updated_at BIGINT,
    updated_by VARCHAR(100),
    deleted_at BIGINT
);

-- Create nodes table
CREATE TABLE IF NOT EXISTS dataloaders.nodes (
    node_id VARCHAR(50) PRIMARY KEY,
    dataflow_id VARCHAR(50) REFERENCES dataloaders.dataflows(id),
    node_name VARCHAR(255),
    node_type VARCHAR(50),
    component_ref VARCHAR(255),
    description TEXT,
    position JSONB,
    node_schema JSONB,
    config JSONB,
    input_ports JSONB,
    output_ports JSONB,
    stage VARCHAR(100),
    stage_order INTEGER,
    depends_on JSONB,
    execution_mode VARCHAR(50),
    resources JSONB,
    error_handling JSONB,
    retry_policy JSONB,
    validations JSONB,
    checkpoint JSONB,
    mapper_config JSONB,
    transformation_metadata JSONB,
    created_at BIGINT,
    created_by VARCHAR(100),
    updated_at BIGINT,
    updated_by VARCHAR(100),
    deleted_at BIGINT
);

-- Create edges table
CREATE TABLE IF NOT EXISTS dataloaders.edges (
    edge_id VARCHAR(50) PRIMARY KEY,
    dataflow_id VARCHAR(50) REFERENCES dataloaders.dataflows(id),
    source_node_id VARCHAR(50) REFERENCES dataloaders.nodes(node_id),
    target_node_id VARCHAR(50) REFERENCES dataloaders.nodes(node_id),
    source_port VARCHAR(50),
    target_port VARCHAR(50),
    edge_type VARCHAR(50),
    condition JSONB,
    async BOOLEAN,
    buffer_size INTEGER,
    transformation JSONB,
    flow_control JSONB,
    lineage JSONB,
    created_at BIGINT,
    created_by VARCHAR(100),
    updated_at BIGINT,
    updated_by VARCHAR(100),
    deleted_at BIGINT
);
