package com.dataflow.dataloaders.entity;

import com.dataflow.dataloaders.jobconfigs.InputField;
import lombok.Data;

import java.util.List;

@Data
public class Mappings extends AuditMetaData{
    public String id;
    public String mappingName;
    public List<InputField> mappings;
    private Boolean isActive;
    private String itemId;
    private Long deletedAt;
    private String mappingDocJson;      // raw mapping DSL JSON from datamapper-codegen
    private String generatedJavaSource; // compiled-ready Java source generated by codegen
    private String generatedClassName;  // fully-qualified class name of the generated mapper
}
