package com.dataflow.dataloaders.jobconfigs;

public enum PROCESSOR_ENUM {
    //Transform enums
    UPPER_CASE, LOWER_CASE, APPEND, PREPEND, TRIM, LPAD, RPAD, REPLACE, MAP_VALUE, DUPLICATE_VALUE, IS_EMPTY,
    IS_EMPTY_REPLACE_FIELD, SUBSTRING,
    DATE_FORMAT, REMOVE_HTML_TAGS, CONCATENATE_COLUMNS, CHANGE_TIMEZONE, ADD_DAYS_CASSANDRA_LOCALDATE, GET_DATE_WITH_ADDITIONAL_TIME, DECRYPT_C360,
    DECRYPT_VOLTAGE, ROUND, REPLACE_NEGATIVE_VALUE,RELATIONSHIP_REFERENCE,
    //null is deprecated, config server reads this enum as a null object instead
    NULL,
    //Mapper enums
    MAP_FIELD, REMOVE_FIELD, MAP_ALL,
    //Filter enums
    IS_NULL, ROW_CONTAINS, PREFIX, CONTAINS, YESTERDAY_DATE_STRING, LENGTH, MINUTES_BEFORE_DATE, REGEX, GREATER_THAN, LESS_THAN_OR_EQUAL,
    //Add Enums
    ADD_COLUMN,
    //Convert Data Type
    NEW_TYPE,
    //Remove Duplicates Enums for Master Processor
    COLUMN, STRING,
    //Extract enums
    JSON_PATH, JSON_PATH_OBJECT, JSON_PATH_ARRAY, MAP_STRING, JSON_PATH_IGNORE_EXCEPTIONS ,
    //OVERRIDING PRIORITY
    PRIORITY,
    //FOR TESTING
    TEST
}
