spring:
  application:
    name: mock-nexus-auth-service

  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  data:
    mongodb:
      uri: mongodb://admin:secret123@localhost:27017/datatable_db?authSource=admin
      database: datatable_db
server:
  port: ${PORT:8080}

gemini:
  api-key: ${GEMINI_API_KEY:}
  url: https://generativelanguage.googleapis.com/v1
